slam_toolbox:
  ros__parameters:

    # Frame settings
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # Mode and timing
    mode: mapping              # online mapping mode
    throttle_scans: 1          # process every scan
    transform_publish_period: 0.05  # faster TF broadcasts
    map_update_interval: 1.0   # update occupancy grid every 1s

    # Disable heavy batch optimizations
    do_loop_closing: false
    optimize_every_n_nodes: 0       # skip global optimization
    pose_graph_max_queue_size: 5    # small queue for async updates

    # Sensor & resolution
    resolution: 0.05
    max_laser_range: 20.0

    # Motion thresholds
    minimum_travel_distance: 0.2   # small travel before adding node
    minimum_travel_heading: 0.1    # small rotation threshold

    # Scan matcher settings
    use_scan_matching: true
    use_scan_barycenter: false

    # Buffer sizes
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0